routes/web.php
<?php

use App\Mail\ExpireSoonEmail;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PlanController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\SignUpController;
use App\Http\Controllers\PaymentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//yang lama
// Route::get('/', function () {
//     return view('utama');
// });

// Route::get('/kelas', function () {
//     return view('kelas');
// });

Route::get('/', function () {
    return view('main');
});

Route::get('/member', [ MemberController::class, 'index'] );

Route::get('/member/login', [ MemberController::class, 'login'] );

Route::get('/member/register', [ MemberController::class, 'register'] );

Route::get('/member/profile', [ MemberController::class, 'profile'] );

Route::get('dashboard', [ 
	MemberController::class, 
	'index'])
	->name('dashboard')
	->middleware(['auth']);



Route::middleware(['auth', 'can:is-admin'])->group(function(){

	Route::resource('admin/user', UserController::class);
	Route::resource('admin/role', RoleController::class);
	Route::resource('admin/plan', PlanController::class);
	Route::get('admin/payment', [ PaymentController::class, 'index' ]);

});

//sign up
Route::get('/signup', [ SignUpController::class, 'index'])->name('signup');
Route::get('/signup/review/{id}', [ SignUpController::class, 'review'] );
Route::post('/signup/go/{payment_gateway}', [ SignUpController::class, 'go'] )->name('signup.go');

// PAYMENT GATEWAY REDIRECT
Route::post('/signup/thankyou/{payment_gateway}', [ SignUpController::class, 'thankyou'] )->name('signup.thankyou');
Route::get('/signup/thankyou/{payment_gateway}', [ SignUpController::class, 'thankyou'] );

// PAYMENT GATEWAY CALLBACK
Route::post('/signup/callback/{payment_gateway}', [ SignUpController::class, 'payment_callback'] )->name('signup.callback');
Route::get('/signup/callback/{payment_gateway}', [ SignUpController::class, 'payment_callback'] );

// EMAIL VIEW
Route::get('/email/expiresoon', function() {
	return new App\Mail\ExpireSoonEmail();
	});

	Route::get('/email/test', function() {

		$data = [
			'name' => 'safwan',
			'expire_at' => '2021-04-21'
		];

		Mail::to('test@gmail.com')->send( new ExpireSoonEmail($data) );
		echo "send Email";	
	});

app/Models/Plan.php
<?php

namespace App\Models;

use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Plan extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'price',
        'duration'
    ];
    


    // public function getPriceAttribute($value)
    // {
    //     return 'RM'.number_format($value / 100, 2);
    // }

    public function getMoneyPriceAttribute()
    {
        return 'RM'.number_format($this->price / 100, 2);
    }


    // AUTAOTOR
    public function setNameAttribute($value)
    {
        $this->attributes['name'] = Str::title($value);
    }

}

app/Http/Controllers/PlanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Plan;
use Illuminate\Http\Request;

class PlanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $plans = Plan::all();
        return view('admin.plan.index', [
            'plans' => $plans
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.plan.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'name' => 'required|min:5|max:100',
            'price' => 'required',
            'duration' => 'required|integer',
        ]);
     
        $data['price'] = abs(floor($data['price'] * 100));
        $plans = Plan::create($data);

        return redirect('/admin/plan')->with('success', "Pengguna {$plans->name} ($plans->id) telah berjaya");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        echo "delete $id";
        $roles = Plan::find($id);
        $roles->delete();

        return redirect('/admin/plan')->with('success', "Pengguna {$roles->name} ($roles->id) telah berjaya Dipadam");
    }
}

resources/views/admin/plan/create.blade.php
@extends('layout.private')

@section('content')

<h1 class="h3 mb-2 text-gray-800">Tambah Pelan Baru</h1>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Isi Maklumat Pelan Langganan Baru</h6>
    </div>
    <div class="card-body">
        <form action="{{ route('plan.store') }}" method="post">
            @csrf

            <div class="mb-3 row">
                <label class="col-sm-2 col-form-label">Nama</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control @error('name') is-invalid @enderror" name="name">
                    @error('name')
                    <div  class="invalid-feedback">
                    {{$message}}
                    </div>
                    @enderror
                    
                </div>
            </div>

            <div class="mb-3 row">
                <label class="col-sm-2 col-form-label">Harga</label>
                <div class="col-sm-10">
                    <input type="number" min="1" max="99999" step="0.01" class="form-control @error('price') is-invalid @enderror" name="price">
                    @error('price')
                    <div class="invalid-feedback">
                    {{$message}}
                    </div>
                    @enderror
                    
                </div>
            </div>

            <div class="mb-3 row">
                <label class="col-sm-2 col-form-label">Tempoh</label>
                <div class="col-sm-10">
                    <input type="number" min="1" max="99999" step="1" class="form-control @error('duration') is-invalid @enderror" name="duration" value="{{  old('duration') }}">
                    @error('duration')
                    <div class="invalid-feedback">
                    {{$message}}
                    </div>
                    @enderror
                    
                </div>
            </div>

            
            <a href="/admin/user" class="btn btn-lg btn-secondary">Batal</a>
            <button class="btn btn-lg btn-primary">Hantar</button>
        </form>
    </div>
</div>


@endsection

resources/views/admin/plan/index.blade.php
@extends('layout.private')

@section('content')

<div class="d-flex justify-content-between mb-3">
<h1 class="h3 mb-2 text-gray-800">Senarai Pelan Langganan</h1>

<a href="/admin/plan/create" class="btn btn-secondary">Tambah Peranan</a>
</div>

@if( session('success'))
<div class="alert alert-success"> {{ session('success') }}</div>
@endif



<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Senarai Pelan Langganan</h6>
    </div>
    <div class="card-body">
     <table class="table stripe">
         <thead>
             <tr>
                 <td>ID</td>
                 <td>Nama</td>
                 <td>Harga</td>
                 <td>Tempoh</td>
                 <td></td>
             </tr>
         </thead>
        <tbody>
            @forelse($plans as $plan)
            <tr>
                <td>{{ $plan->id}}</td>
                <td>{{ $plan->name}}</td>
                <td>{{ $plan->money_price }}</td>
                <td>{{ $plan->duration}}</td>
                <td>
                    <a href="{{ route('plan.edit', $plan->id)}}" class="btn btn-sm btn-primary">Edit</a>
                   
                    <form method="post" class="d-inline" 
                    action="{{ route('plan.destroy', $plan->id) }}" 
                    onsubmit="return confirm('Are your sure you want to delete {{$plan->name}} ({{$plan->id}})?');">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                    </form>
                </td>
               
                
            </tr>
            @empty
            <tr>
                <td colspan="5" class="text-center" style= "height:50px;"> 
                    Anda belum membuat apa-apa langganan
                </td>
            </tr>
            @endforelse
        </tbody>
     </table>
    </div>
</div>


@endsection