routes/web.php
<?php

use App\Mail\ExpireSoonEmail;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PlanController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\SignUpController;
use App\Http\Controllers\PaymentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//yang lama
// Route::get('/', function () {
//     return view('utama');
// });

// Route::get('/kelas', function () {
//     return view('kelas');
// });

Route::get('/', function () {
    return view('main');
});

Route::get('/member', [ MemberController::class, 'index'] );

Route::get('/member/login', [ MemberController::class, 'login'] );

Route::get('/member/register', [ MemberController::class, 'register'] );

Route::get('/member/profile', [ MemberController::class, 'profile'] );

Route::get('dashboard', [ 
	MemberController::class, 
	'index'])
	->name('dashboard')
	->middleware(['auth']);



Route::middleware(['auth', 'can:is-admin'])->group(function(){

	Route::resource('admin/user', UserController::class);
	Route::resource('admin/role', RoleController::class);
	Route::resource('admin/plan', PlanController::class);
	Route::get('admin/payment', [ PaymentController::class, 'index' ]);

});

//sign up
Route::get('/signup', [ SignUpController::class, 'index'])->name('signup');
Route::get('/signup/review/{id}', [ SignUpController::class, 'review'] );
Route::post('/signup/go/{payment_gateway}', [ SignUpController::class, 'go'] )->name('signup.go');

// PAYMENT GATEWAY REDIRECT
Route::post('/signup/thankyou/{payment_gateway}', [ SignUpController::class, 'thankyou'] )->name('signup.thankyou');
Route::get('/signup/thankyou/{payment_gateway}', [ SignUpController::class, 'thankyou'] );

// PAYMENT GATEWAY CALLBACK
Route::post('/signup/callback/{payment_gateway}', [ SignUpController::class, 'payment_callback'] )->name('signup.callback');
Route::get('/signup/callback/{payment_gateway}', [ SignUpController::class, 'payment_callback'] );

// EMAIL VIEW
Route::get('/email/expiresoon', function() {
	return new App\Mail\ExpireSoonEmail();
	});

	Route::get('/email/test', function() {

		$data = [
			'name' => 'safwan',
			'expire_at' => '2021-04-21'
		];

		Mail::to('test@gmail.com')->send( new ExpireSoonEmail($data) );
		echo "send Email";	
	});

app/Models/Subscription.php
<?php

namespace App\Models;

use Illuminate\Support\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Subscription extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'last_payment_id',
        'expire_at',
    ];

    // CASTING
    protected $casts = [
        'expire_at' => 'datetime'
    ];

    
    public function getActiveAttribute(){

        return $this->expire_at->greaterThan(Carbon::now());
    
    }

    public function getDaysLeftAttribute(){

        if($this->active){
            return $this->expire_at->diffInDays();
        }

        return 0;
    }

}

app/Models/User.php
<?php

namespace App\Models;

use App\Models\Subscription;
use Illuminate\Support\Carbon;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Support\Facades\Hash;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements MustverifyEmail
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles() {
        return $this->belongsToMany( Role::class );
    }

    // MUTATOR
    // public function setPasswordAttribute($value){

    //  return $this->password = Hash::make($value); 
     
    // }

    public function subscription(){

        return $this->hasOne(Subscription::class);

    }

    
    public function payments() {
        return $this->hasMany( Payment::class );
    }
    
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{

    public function __construct() {

    
    }



    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        // if (! Gate::allows('is-admin')) {
        //     abort(403);
        // }
        
        // $users = User::all();
        // $users = User::paginate(10);

        $users = User::with('subscription')->paginate(20);

        return view('admin.user.index', [
            'users' => $users
        ]);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $form_data = $request->validate([
            'name' => 'required|min:5|max:255',
            'email' => 'required|email',
            'password' => 'required|confirmed'
        ]);
        
        $form_data['password'] = Hash::make( $form_data['password']);

        $user = User::create($form_data);

        return redirect('admin/user')->with('success', "Pengguna {$user->id} ($user->id) Telah berjaya Disimpan");

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // echo "add edit form ";

        $user = User::find($id);
        $roles = Role::all();

        // dd($users);

        return view('admin.user.edit', [
            'user' => $user,
            'roles' => $roles
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);

        $form_data = $request->validate([
            'name' => 'required|min:5|max:255',
            'email' => 'required|email'
        ]);
        
        $user->name = $form_data['name'];
        $user->email = $form_data['email'];

        $user->save();

        $user->roles()->sync( $request->roles);

        return redirect('admin/user')->with('success', "Pengguna {$user->id} ($id) Telah berjaya dikemaskini");
        
        // echo "updating id";
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        echo "delete $id";
        $roles = User::find($id);
        $roles->delete();

        return redirect('/admin/user')->with('success', "Pengguna {$roles->name} ($roles->id) telah berjaya Dipadam");
    }
}

resources/views/admin/user/create.blade.php
@extends('layout.private')

@section('content')

<h1 class="h3 mb-2 text-gray-800">Tambah Pengguna Baru</h1>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Isi Maklumat Pengguna Baru</h6>
    </div>
    <div class="card-body">
        <form action="{{ route('user.store') }}" method="post">
            @csrf

            <div class="mb-3 row">
                <label class="col-sm-2 col-form-label">Nama</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control @error('name') is-invalid @enderror" name="name">
                    @error('name')
                    <div id="validationServer03Feedback" class="invalid-feedback">
                    {{$message}}
                    </div>
                    @enderror
                    
                </div>
            </div>

            <div class="mb-3 row">
                <label class="col-sm-2 col-form-label">Email</label>
                <div class="col-sm-10">
                    <input type="email" class="form-control @error('email') is-invalid @enderror" name="email">
                    @error('email')
                    <div id="validationServer03Feedback" class="invalid-feedback">
                    {{$message}}
                    </div>
                    @enderror
                </div>
            </div>

            <div class="mb-3 row">
                <label class="col-sm-2 col-form-label">Password</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control @error('password') is-invalid @enderror" name="password">
                    @error('password')
                    <div id="validationServer03Feedback" class="invalid-feedback">
                    {{$message}}
                    </div>
                    @enderror
                </div>
            </div>

            <div class="mb-3 row">
                <label class="col-sm-2 col-form-label">Confirm Password</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control @error('password_confirmation') is-invalid @enderror" name="password_confirmation">
                    @error('password_confirmation')
                    <div id="validationServer03Feedback" class="invalid-feedback">
                    {{$message}}
                    </div>
                    @enderror
                </div>
            </div>


            
            <a href="/admin/user" class="btn btn-lg btn-secondary">Batal</a>
            <button class="btn btn-lg btn-primary">Hantar</button>
        </form>
    </div>
</div>


@endsection

resources/views/admin/user/edit.blade.php
@extends('layout.private')

@section('content')

<h1 class="h3 mb-2 text-gray-800">Senarai Pengguna</h1>


<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">{{ $user->name}}</h6>
    </div>
    <div class="card-body">
        <form action="{{ route('user.update', $user->id)}}" method="post">
            @csrf
            @method('put')

            <div class="mb-3 row">
                <label class="col-sm-2 col-form-label">Nama</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name',$user->name) }}">
                    @error('name')
                    <div id="validationServer03Feedback" class="invalid-feedback">
                    {{$message}}
                    </div>
                    @enderror
                    
                </div>
            </div>

            <div class="mb-3 row">
                <label class="col-sm-2 col-form-label">Email</label>
                <div class="col-sm-10">
                    <input type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email',$user->email) }}" >
                    @error('email')
                    <div id="validationServer03Feedback" class="invalid-feedback">
                    {{$message}}
                    </div>
                    @enderror
                </div>
            </div>

            <div class="mb-3 row">
                <label class="col-sm-2 col-form-label">Email</label>
                <div class="col-sm-10">
                    @foreach($roles as $role)
                    <div class="custom-control custom-checkbox small">
                        <input
                        @if(in_array($role->id,$user->roles->pluck('id')->toArray()) )
                        checked
                        @endif
                        type="checkbox" class="custom-control-input" name="roles[]" value="{{$role->id}}" id=role_{{$role->id}}>
                        <label class="custom-control-label" for="role_{{$role->id}}">{{$role->name}}</label>
                    </div>
                    @endforeach
                </div>
            </div>

            <!-- <pre>
                 @foreach($user->roles()->pluck('name') as $role)
                 <li>{{$role}}</li>
                 @endforeach
            </pre> -->    

            <button class="btn btn-lg btn-primary">Simpan</button>
        </form>
    </div>
</div>

@endsection

resources/views/admin/user/index.blade.php
@extends('layout.private')

@section('content')

<div class="d-flex justify-content-between mb-3">
<h1 class="h3 mb-2 text-gray-800">Senarai Pengguna</h1>

<a href="/admin/user/create" class="btn btn-secondary">Tambah Pengguna</a>
</div>

@if( session('success'))
<div class="alert alert-success">{{ session('success') }}</div>
@endif

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">

            <table class="table">
                <thread>
                    <tr>
                        <th>ID</th>
                        <th>NAMA</th>
                        <th>EMAIL</th>
                        <th>Status</th>
                        <th>Tarikh Tinggal</th>
                        <th></th>
                    </tr>
                </thread>
                <tbody>
                    @foreach($users as $user)
                    <tr>
                        <td>{{ $user->id}}</td>
                        <td>{{ $user->name}}</td>
                        <td>{{ $user->email}}</td>
                        <td>
                            @if( $user->subscription && $user->subscription->active)
                            <span class="badge badge-success">OK</span>
                            @else 
                            <span class="badge badge-danger">LUPUT</span>
                            @endif
                        </td>
                        <td>
                            @if( $user->subscription)
                            {{ $user->subscription->expire_at->toFormattedDateString() }}
                            ({{ $user->subscription->days_left }} Hari)
                            @else 
                            0
                            @endif
                        </td>
                        <td>
                            <a href="#" class="btn btn-sm btn-danger">DELETE</a>
                            <a href="{{ route('user.edit', $user->id) }}" class="btn btn-sm btn-primary">EDIT</a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>

            {{ $users->links() }}
        </div>

    </div>
</div>
@endsection